/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "on-secondary-container": "#b4b5b5",
        "surface-elevated": "#0F0F0F",
        "surface-container-highest": "#353535",
        "tertiary-container": "#f2a5ff",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "secondary": "#c6c6c7",
        "on-primary": "#223600",
        "tertiary-fixed": "#fdd6ff",
        "outline": "#8c947b",
        "error": "#ffb4ab",
        "surface": "#131313",
        "inverse-primary": "#446900",
        "on-tertiary": "#520e62",
        "on-secondary-fixed-variant": "#454747",
        "surface-container-lowest": "#0e0e0e",
        "surface-variant": "#353535",
        "surface-dim": "#131313",
        "on-surface-variant": "#c2caaf",
        "on-surface": "#e2e2e2",
        "surface-card": "#1C1C1C",
        "on-primary-container": "#385700",
        "tertiary-fixed-dim": "#f4aeff",
        "on-tertiary-container": "#743284",
        "on-primary-fixed": "#121f00",
        "on-secondary": "#2f3131",
        "primary-fixed-dim": "#95da11",
        "surface-tint": "#95da11",
        "surface-bright": "#393939",
        "secondary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#6b2a7b",
        "secondary-container": "#454747",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#340042",
        "on-error": "#690005",
        "outline-variant": "#424935",
        "on-background": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "primary-fixed": "#aff838",
        "surface-container-low": "#1b1b1b",
        "off-white": "#FAF5EF",
        "tertiary": "#fbceff",
        "surface-container": "#1f1f1f",
        "error-container": "#93000a",
        "primary": "#a9f131",
        "inverse-on-surface": "#303030",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#334f00",
        "primary-container": "#8fd400"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "gutter": "1.5rem",
        "stack-xl": "8rem",
        "border-width": "3px",
        "stack-md": "2rem",
        "stack-lg": "4rem",
        "margin-desktop": "5rem"
      },
      fontFamily: {
        "display-lg-mobile": ["Bricolage Grotesque"],
        "body-md": ["Manrope"],
        "headline-md": ["Bricolage Grotesque"],
        "headline-lg": ["Bricolage Grotesque"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Manrope"],
        "label-md": ["JetBrains Mono"],
        "display-lg": ["Bricolage Grotesque"],
        "sans": ["Manrope", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "display-lg-mobile": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "800"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "display-lg": ["72px", {"lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      },
      borderWidth: {
        "1": "1px",
        "3": "3px",
      }
    },
  },
  plugins: [],
}
